### ISSUE TITLE
Make field names settable within html

### ISSUE THREAD

**Issue by lucadegasperi** [ianlandsman/Honeypot#2]
Hi Ian,

It would be great to have the ability to set the name of the fields directly from the html declaration, something similar to this:

``` php
{{ Form::honeypot('fieldname', 'speed') }}
```

**Comment by ianlandsman** [comment]
Hmm, that's interesting. Would let you use different names on different forms.

Ok let me take a look.

**Comment by lucadegasperi** [comment]
that would also skip the need to get the bundle's configuration data for the validation. making it look cleaner imho.

**Comment by ianlandsman** [comment]
yeah almost done. this is like 10 lines of code now :)

**Comment by ianlandsman** [comment]
OK try it now, see if it's working.

**Comment by lucadegasperi** [comment]
Ok it's fine now! Thanks for the quick change ;)
